
#Server Details
server.port=${PORT:4000}
server.error.include-stacktrace=never

#Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/notificationservice?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:serviceAdmin}
spring.datasource.password=${DB_PASSWORD:serviceAdmin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=${SHOW_SQL:false}
