spring.jpa.hibernate.ddl-auto=update
#Local defaults. For AWS, set DB_URL to the RDS endpoint
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/paymentservice?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:serviceAdmin}
spring.datasource.password=${DB_PASSWORD:serviceAdmin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=${SHOW_SQL:false}
server.port=${PORT:8080}
razorpay.key.id = ${RAZORPAY_KEY_ID}
razorpay.key.secret = ${RAZORPAY_KEY_SECRET}
stripe.key.id = ${STRIPE_KEY_ID}
stripe.key.secret = ${STRIPE_KEY_SECRET}
stripe.endpoint.secret = ${STRIPE_ENDPOINT_SECRET}
