spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=${DATABASE_URL}
spring.datasource.url=${LOCALHOST_DB_URL}
#spring.datasource.url=${AWS_DB_URL}
#spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.username=${LOCALHOST_DB_USERNAME}
spring.datasource.password=${LOCALHOST_DB_PASSWORD}
#spring.datasource.username=${AWS_DB_USERNAME}
#spring.datasource.password=${AWS_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql=true
logging.level.org.springframework.security=trace
server.port=8080
razorpay.key.id = ${RAZORPAY_KEY_ID}
razorpay.key.secret = ${RAZORPAY_KEY_SECRET}
stripe.key.id = ${STRIPE_KEY_ID}
stripe.key.secret = ${STRIPE_KEY_SECRET}